### ISSUE TITLE
Überarbeitung Lastenheft

### ISSUE THREAD

**Issue by lightning1** [codephant/tud-swt2-2014#1]
- Qualitätsanforderungen ausformulieren
- Differenzierung der Produktdaten (Datenstruktur)
- Produktleistungen ausformulieren

**Comment by mascheck** [comment]
Bei den Produktleistungen fliegen dann da die Stichpunkte raus und statt dem ganzen nen fliestext oder zu jedem Punkt mehr Text?

Was ist mit konkreter mit Differenzierung der Produktdaten gemeint?

DIe Qualitätsanforderungen waren in der Vorlage auch nur ne Tabelle? Trotzdem ausformulieren, ja?

**Comment by lightning1** [comment]
Bei Produktleistungen war das als Fließtext gedacht.

Differenzierung der Produktdaten am Beispiel Adresse:
- Land
- Postleitzahl
- Ort
- Straße
- Hausnummer
- Adresszusatz

Zu den Qualitätsanforderungen:
Eine Konkretisierung der einzelnen Bereiche sollte stattfinden, z.B. Benutzbarkeit muss (u.a.) im Sinne von "vielen schnellen Systemaktionen" für die Ausleihe beleuchtet werden.

**Comment by mascheck** [comment]
Ist erledigt. Schaut nochmal drüber. Und das PDF muss neu compiliert werden, ich hab keine Ahnung wie man das unter windows macht ;)
