### ISSUE TITLE
Klassendiagramme für das Pflichtenheft

### ISSUE THREAD

**Issue by lightning1** [codephant/tud-swt2-2014#4]
- einzelne Diagramme für Daten (incl. Attribute und Methoden)
- Übersichtsdiagramm für Beziehungen zwischen Daten (ohne Attribute und Methoden)

**Comment by jvrsgsty** [comment]
Klassendiagramme für Pflichtenheft wurden "commited". 
Wenn es noch Änderungen braucht, bitte an uns wenden. 

Achtung: PDFs müssen noch kompiliert sein!
